# Generated by Django 2.1.5 on 2019-03-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='text_file',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
