# Generated by Django 2.1.5 on 2019-03-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pd', '0002_auto_20190319_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='role_name',
            field=models.CharField(choices=[('1', 'Sales Representative'), ('2', 'Sales head'), ('3', 'Engineer'), ('4', 'Engineering Head'), ('5', 'Business Development Representative'), ('6', 'Business Development Head'), ('7', 'Admin'), ('8', 'HR'), ('9', 'Consultant'), ('10', 'Business Head'), ('11', 'SCM')], max_length=40),
        ),
    ]
