# Generated by Django 2.1.5 on 2019-03-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pd', '0004_user_master_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code_lookup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='code_lookup',
            name='created_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='code_lookup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='code_lookup',
            name='updated_by',
            field=models.IntegerField(null=True),
        ),
    ]
