# Generated by Django 2.1.5 on 2019-03-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pd', '0005_auto_20190319_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_master',
            name='status',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
