# Generated by Django 2.1.5 on 2019-03-25 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pd', '0007_auto_20190325_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_master',
            name='role',
        ),
    ]
