# Generated by Django 2.1.5 on 2019-03-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pd', '0008_remove_user_master_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='code_lookup',
            name='key_code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='code_lookup',
            name='key_1',
            field=models.CharField(max_length=50),
        ),
    ]
